
/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/09/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest
 *
 * @constructor
 */
CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest = function (obj) {
    if(!obj) {
        this.id = null;     
        this.dataLink = null;     
        this.hints = null;     
        //Append to variable dictionary
        this._variableDict['dataLink'] = 'data_link';
    } else {
        this.id = obj.id;
        this.dataLink = obj.data_link;
        this.hints = obj.hints;
        //Append to variable dictionary
        this._variableDict['dataLink'] = 'data_link';
    }
};

CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest.prototype = new BaseModel();
CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest.prototype.constructor = CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string} value 
 */
CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest.prototype.getDataLink = function() {
    return this.dataLink;
};

/**
 * Setter for DataLink
 * 
 * @param {string} value 
 */
CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest.prototype.setDataLink = function(value) {
    this.dataLink = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest.prototype.getHints = function() {
    return this.hints;
};

/**
 * Setter for Hints
 * 
 * @param {array} value 
 */
CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest.prototype.setHints = function(value) {
    this.hints = value;
};


module.exports = CreateANewCallRecordAndTriggerRecognitionAlgorithmExecutionRequest;