
/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/09/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of GetARepresentativeResponse
 *
 * @constructor
 */
GetARepresentativeResponse = function (obj) {
    if(!obj) {
        this.id = null;     
        this.name = null;     
        this.createdAt = null;     
        this.gender = null;     
        this.active = null;     
        this.links = null;     
        //Append to variable dictionary
        this._variableDict['createdAt'] = 'created_at';
    } else {
        this.id = obj.id;
        this.name = obj.name;
        this.createdAt = obj.created_at;
        this.gender = obj.gender;
        this.active = obj.active;
        this.links = obj.links;
        //Append to variable dictionary
        this._variableDict['createdAt'] = 'created_at';
    }
};

GetARepresentativeResponse.prototype = new BaseModel();
GetARepresentativeResponse.prototype.constructor = GetARepresentativeResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetARepresentativeResponse.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string} value 
 */
GetARepresentativeResponse.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetARepresentativeResponse.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
GetARepresentativeResponse.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetARepresentativeResponse.prototype.getCreatedAt = function() {
    return this.createdAt;
};

/**
 * Setter for CreatedAt
 * 
 * @param {string} value 
 */
GetARepresentativeResponse.prototype.setCreatedAt = function(value) {
    this.createdAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetARepresentativeResponse.prototype.getGender = function() {
    return this.gender;
};

/**
 * Setter for Gender
 * 
 * @param {string} value 
 */
GetARepresentativeResponse.prototype.setGender = function(value) {
    this.gender = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {bool}
 */
GetARepresentativeResponse.prototype.getActive = function() {
    return this.active;
};

/**
 * Setter for Active
 * 
 * @param {bool} value 
 */
GetARepresentativeResponse.prototype.setActive = function(value) {
    this.active = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
GetARepresentativeResponse.prototype.getLinks = function() {
    return this.links;
};

/**
 * Setter for Links
 * 
 * @param {array} value 
 */
GetARepresentativeResponse.prototype.setLinks = function(value) {
    this.links = value;
};


module.exports = GetARepresentativeResponse;