
/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/09/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of RetrieveAModelResponse
 *
 * @constructor
 */
RetrieveAModelResponse = function (obj) {
    if(!obj) {
        this.createdAt = null;     
        this.gender = null;     
        this.id = null;     
        this.mixtures = null;     
        this.name = null;     
        this.numExamples = null;     
        this.quality = null;     
        this.trainingSource = null;     
        this.ubmId = null;     
        this.ubmName = null;     
        //Append to variable dictionary
        this._variableDict['createdAt'] = 'created_at';
        this._variableDict['numExamples'] = 'num_examples';
        this._variableDict['trainingSource'] = 'training_source';
        this._variableDict['ubmId'] = 'ubm_id';
        this._variableDict['ubmName'] = 'ubm_name';
    } else {
        this.createdAt = obj.created_at;
        this.gender = obj.gender;
        this.id = obj.id;
        this.mixtures = obj.mixtures;
        this.name = obj.name;
        this.numExamples = obj.num_examples;
        this.quality = obj.quality;
        this.trainingSource = obj.training_source;
        this.ubmId = obj.ubm_id;
        this.ubmName = obj.ubm_name;
        //Append to variable dictionary
        this._variableDict['createdAt'] = 'created_at';
        this._variableDict['numExamples'] = 'num_examples';
        this._variableDict['trainingSource'] = 'training_source';
        this._variableDict['ubmId'] = 'ubm_id';
        this._variableDict['ubmName'] = 'ubm_name';
    }
};

RetrieveAModelResponse.prototype = new BaseModel();
RetrieveAModelResponse.prototype.constructor = RetrieveAModelResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAModelResponse.prototype.getCreatedAt = function() {
    return this.createdAt;
};

/**
 * Setter for CreatedAt
 * 
 * @param {string} value 
 */
RetrieveAModelResponse.prototype.setCreatedAt = function(value) {
    this.createdAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAModelResponse.prototype.getGender = function() {
    return this.gender;
};

/**
 * Setter for Gender
 * 
 * @param {string} value 
 */
RetrieveAModelResponse.prototype.setGender = function(value) {
    this.gender = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAModelResponse.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string} value 
 */
RetrieveAModelResponse.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
RetrieveAModelResponse.prototype.getMixtures = function() {
    return this.mixtures;
};

/**
 * Setter for Mixtures
 * 
 * @param {int} value 
 */
RetrieveAModelResponse.prototype.setMixtures = function(value) {
    this.mixtures = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAModelResponse.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
RetrieveAModelResponse.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
RetrieveAModelResponse.prototype.getNumExamples = function() {
    return this.numExamples;
};

/**
 * Setter for NumExamples
 * 
 * @param {int} value 
 */
RetrieveAModelResponse.prototype.setNumExamples = function(value) {
    this.numExamples = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
RetrieveAModelResponse.prototype.getQuality = function() {
    return this.quality;
};

/**
 * Setter for Quality
 * 
 * @param {int} value 
 */
RetrieveAModelResponse.prototype.setQuality = function(value) {
    this.quality = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAModelResponse.prototype.getTrainingSource = function() {
    return this.trainingSource;
};

/**
 * Setter for TrainingSource
 * 
 * @param {string} value 
 */
RetrieveAModelResponse.prototype.setTrainingSource = function(value) {
    this.trainingSource = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAModelResponse.prototype.getUbmId = function() {
    return this.ubmId;
};

/**
 * Setter for UbmId
 * 
 * @param {string} value 
 */
RetrieveAModelResponse.prototype.setUbmId = function(value) {
    this.ubmId = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAModelResponse.prototype.getUbmName = function() {
    return this.ubmName;
};

/**
 * Setter for UbmName
 * 
 * @param {string} value 
 */
RetrieveAModelResponse.prototype.setUbmName = function(value) {
    this.ubmName = value;
};


module.exports = RetrieveAModelResponse;