
/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/09/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of RetrieveACallResponse
 *
 * @constructor
 */
RetrieveACallResponse = function (obj) {
    if(!obj) {
        this.id = null;     
        this.dataLink = null;     
        this.createdAt = null;     
        this.hints = null;     
        this.rep = null;     
        this.client = null;     
        this.status = null;     
        //Append to variable dictionary
        this._variableDict['dataLink'] = 'data_link';
        this._variableDict['createdAt'] = 'created_at';
    } else {
        this.id = obj.id;
        this.dataLink = obj.data_link;
        this.createdAt = obj.created_at;
        this.hints = obj.hints;
        this.rep = obj.rep;
        this.client = obj.client;
        this.status = obj.status;
        //Append to variable dictionary
        this._variableDict['dataLink'] = 'data_link';
        this._variableDict['createdAt'] = 'created_at';
    }
};

RetrieveACallResponse.prototype = new BaseModel();
RetrieveACallResponse.prototype.constructor = RetrieveACallResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveACallResponse.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string} value 
 */
RetrieveACallResponse.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveACallResponse.prototype.getDataLink = function() {
    return this.dataLink;
};

/**
 * Setter for DataLink
 * 
 * @param {string} value 
 */
RetrieveACallResponse.prototype.setDataLink = function(value) {
    this.dataLink = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveACallResponse.prototype.getCreatedAt = function() {
    return this.createdAt;
};

/**
 * Setter for CreatedAt
 * 
 * @param {string} value 
 */
RetrieveACallResponse.prototype.setCreatedAt = function(value) {
    this.createdAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
RetrieveACallResponse.prototype.getHints = function() {
    return this.hints;
};

/**
 * Setter for Hints
 * 
 * @param {array} value 
 */
RetrieveACallResponse.prototype.setHints = function(value) {
    this.hints = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
RetrieveACallResponse.prototype.getRep = function() {
    return this.rep;
};

/**
 * Setter for Rep
 * 
 * @param {array} value 
 */
RetrieveACallResponse.prototype.setRep = function(value) {
    this.rep = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
RetrieveACallResponse.prototype.getClient = function() {
    return this.client;
};

/**
 * Setter for Client
 * 
 * @param {array} value 
 */
RetrieveACallResponse.prototype.setClient = function(value) {
    this.client = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveACallResponse.prototype.getStatus = function() {
    return this.status;
};

/**
 * Setter for Status
 * 
 * @param {string} value 
 */
RetrieveACallResponse.prototype.setStatus = function(value) {
    this.status = value;
};


module.exports = RetrieveACallResponse;