
/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/09/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of RetrieveAListOfAllClientsResponse
 *
 * @constructor
 */
RetrieveAListOfAllClientsResponse = function (obj) {
    if(!obj) {
        this.id = null;     
        this.name = null;     
        this.createdAt = null;     
        this.gender = null;     
        //Append to variable dictionary
        this._variableDict['createdAt'] = 'created_at';
    } else {
        this.id = obj.id;
        this.name = obj.name;
        this.createdAt = obj.created_at;
        this.gender = obj.gender;
        //Append to variable dictionary
        this._variableDict['createdAt'] = 'created_at';
    }
};

RetrieveAListOfAllClientsResponse.prototype = new BaseModel();
RetrieveAListOfAllClientsResponse.prototype.constructor = RetrieveAListOfAllClientsResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAListOfAllClientsResponse.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string} value 
 */
RetrieveAListOfAllClientsResponse.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAListOfAllClientsResponse.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
RetrieveAListOfAllClientsResponse.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAListOfAllClientsResponse.prototype.getCreatedAt = function() {
    return this.createdAt;
};

/**
 * Setter for CreatedAt
 * 
 * @param {string} value 
 */
RetrieveAListOfAllClientsResponse.prototype.setCreatedAt = function(value) {
    this.createdAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RetrieveAListOfAllClientsResponse.prototype.getGender = function() {
    return this.gender;
};

/**
 * Setter for Gender
 * 
 * @param {string} value 
 */
RetrieveAListOfAllClientsResponse.prototype.setGender = function(value) {
    this.gender = value;
};


module.exports = RetrieveAListOfAllClientsResponse;