/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/09/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "http://recog.calltrackingmetrics.com/v1"

};

module.exports = configuration;

